# Generated by Django 3.0.3 on 2020-06-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200605_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(null=True)),
                ('category_name', models.TextField()),
                ('category_url', models.TextField()),
            ],
        ),
    ]
