# Generated by Django 3.0.3 on 2020-06-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='barcode',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
