# Generated by Django 3.0.3 on 2020-06-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200607_2359'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='substitute',
            constraint=models.UniqueConstraint(fields=('user_id', 'aliment_id'), name='saved_substitute'),
        ),
    ]
