python:
    - '3.7'

before_script:
    - 'pip install -r requirements.txt'
        
env: DJANGO_SETTINGS_MODULE='purbeurre_project.settings'

services:
    - postgresql

env: DJANGO_SETTINGS_MODULE=purbeurre_project.settings.travis

script: 
    - python manage.py test