language: python

python:
    - '3.7'

before_script:
    - 'pip install -r requirements.txt'

services:
    - postgresql

env: DJANGO_SETTINGS_MODULE=purbeurre_project.settings

script: 
    - python manage.py test